services:
  # Backend API Service
  - type: web
    name: oxiwell-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URL
        fromDatabase:
          name: oxiwell-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 2000
      - key: FRONTEND_URL
        value: https://oxiwell.onrender.com

  # Frontend Static Site Service
  - type: static
    name: oxiwell
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    routes:
      - source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://oxiwell-backend.onrender.com/api

databases:
  - name: oxiwell-db
    databaseName: oxiwell
    plan: free
